"""plan_inyeccion

Revision ID: d5c8fa4b3aa0
Revises: 004_add_permisos_tabs
Create Date: 2026-05-07 11:50:14.676316-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c8fa4b3aa0'
down_revision: Union[str, None] = '004_add_permisos_tabs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_inyeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('numero_parte', sa.String(length=100), nullable=False),
    sa.Column('plan_piezas', sa.Integer(), nullable=False),
    sa.Column('piezas_producidas', sa.Integer(), nullable=True),
    sa.Column('orden_secuencia', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_ultimo_inicio', sa.DateTime(), nullable=True),
    sa.Column('tiempo_acumulado_seg', sa.Integer(), nullable=True),
    sa.Column('en_paro', sa.Boolean(), nullable=True),
    sa.Column('paros', sa.JSON(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_inyeccion_id'), 'plan_inyeccion', ['id'], unique=False)
    op.create_index(op.f('ix_plan_inyeccion_maquina'), 'plan_inyeccion', ['maquina'], unique=False)
    op.create_index(op.f('ix_plan_inyeccion_numero_parte'), 'plan_inyeccion', ['numero_parte'], unique=False)
    op.create_index(op.f('ix_plan_inyeccion_prioridad'), 'plan_inyeccion', ['prioridad'], unique=False)
    op.create_index(op.f('ix_plan_inyeccion_status'), 'plan_inyeccion', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_inyeccion_status'), table_name='plan_inyeccion')
    op.drop_index(op.f('ix_plan_inyeccion_prioridad'), table_name='plan_inyeccion')
    op.drop_index(op.f('ix_plan_inyeccion_numero_parte'), table_name='plan_inyeccion')
    op.drop_index(op.f('ix_plan_inyeccion_maquina'), table_name='plan_inyeccion')
    op.drop_index(op.f('ix_plan_inyeccion_id'), table_name='plan_inyeccion')
    op.drop_table('plan_inyeccion')
    # ### end Alembic commands ###