"""add_clientes_table

Revision ID: eb2fbe5b186d
Revises: 20260609_add_psi_snapshots
Create Date: 2026-06-09 11:34:41.347664-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb2fbe5b186d'
down_revision: Union[str, None] = '20260609_add_psi_snapshots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=50), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=100), nullable=True),
    sa.Column('contacto_email', sa.String(length=100), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=100), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('score_cliente', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cliente_id'), 'clientes', ['cliente_id'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('config_alertas_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('stock_maximo', sa.Float(), nullable=True),
    sa.Column('dias_rotacion', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('notificar_a', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_alertas_stock_id'), 'config_alertas_stock', ['id'], unique=False)
    op.create_index(op.f('ix_config_alertas_stock_sku'), 'config_alertas_stock', ['sku'], unique=False)
    op.create_table('conteos_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteo_id', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('zona', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('total_diferencia', sa.Float(), nullable=True),
    sa.Column('aprobado_por', sa.String(length=100), nullable=True),
    sa.Column('creado_por', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conteo_id')
    )
    op.create_index(op.f('ix_conteos_fisicos_id'), 'conteos_fisicos', ['id'], unique=False)
    op.create_table('ordenes_picking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picking_id', sa.String(length=100), nullable=False),
    sa.Column('tipo_origen', sa.String(length=20), nullable=False),
    sa.Column('origen_id', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('zona_staging', sa.String(length=200), nullable=True),
    sa.Column('creado_por', sa.String(length=100), nullable=False),
    sa.Column('asignado_a', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_picking_id'), 'ordenes_picking', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_picking_picking_id'), 'ordenes_picking', ['picking_id'], unique=True)
    op.create_table('cliente_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id_fk', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('impacto', sa.Float(), nullable=False),
    sa.Column('referencia_id', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registrado_por', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id_fk'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_contactos_empresa_area'), table_name='contactos_empresa')
    op.drop_table('contactos_empresa')
    op.drop_table('configuracion_empresa')
    op.alter_column('lotes_inventario', 'bultos',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ordenes_compra', 'iva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('psi_snapshots', 'coverage_ref_dday',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_ref_d1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_oven_dday',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_oven_d1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_need_dday',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_covered_dday',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_need_d1',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_covered_d1',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_need_dday',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_covered_dday',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_need_d1',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_covered_d1',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('psi_snapshots_fecha_key'), 'psi_snapshots', type_='unique')
    op.drop_index(op.f('ix_psi_snapshots_fecha'), table_name='psi_snapshots')
    op.create_index(op.f('ix_psi_snapshots_fecha'), 'psi_snapshots', ['fecha'], unique=True)
    op.alter_column('ubicaciones', 'tipo_zona',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ubicaciones', 'permite_mixing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ubicaciones', 'activa',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ubicaciones', 'activa',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('ubicaciones', 'permite_mixing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ubicaciones', 'tipo_zona',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'ALMACEN'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_psi_snapshots_fecha'), table_name='psi_snapshots')
    op.create_index(op.f('ix_psi_snapshots_fecha'), 'psi_snapshots', ['fecha'], unique=False)
    op.create_unique_constraint(op.f('psi_snapshots_fecha_key'), 'psi_snapshots', ['fecha'], postgresql_nulls_not_distinct=False)
    op.alter_column('psi_snapshots', 'oven_covered_d1',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_need_d1',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_covered_dday',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'oven_need_dday',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_covered_d1',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_need_d1',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_covered_dday',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'ref_need_dday',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_oven_d1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_oven_dday',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_ref_d1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('psi_snapshots', 'coverage_ref_dday',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('ordenes_compra', 'iva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('lotes_inventario', 'bultos',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_table('configuracion_empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('rfc', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('representante_legal', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('regimen_fiscal', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cp', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), server_default=sa.text("'México'::character varying"), autoincrement=False, nullable=True),
    sa.Column('banco', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cuenta', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('clabe', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('configuracion_empresa_pkey'))
    )
    op.create_table('contactos_empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('puesto', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ext', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('celular', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('es_principal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('horario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contactos_empresa_pkey'))
    )
    op.create_index(op.f('ix_contactos_empresa_area'), 'contactos_empresa', ['area'], unique=False)
    op.drop_table('cliente_eventos')
    op.drop_index(op.f('ix_ordenes_picking_picking_id'), table_name='ordenes_picking')
    op.drop_index(op.f('ix_ordenes_picking_id'), table_name='ordenes_picking')
    op.drop_table('ordenes_picking')
    op.drop_index(op.f('ix_conteos_fisicos_id'), table_name='conteos_fisicos')
    op.drop_table('conteos_fisicos')
    op.drop_index(op.f('ix_config_alertas_stock_sku'), table_name='config_alertas_stock')
    op.drop_index(op.f('ix_config_alertas_stock_id'), table_name='config_alertas_stock')
    op.drop_table('config_alertas_stock')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cliente_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###