"""sync defaults fk and nullables

Revision ID: 5b0b45019a2a
Revises: b07f06943d3b
Create Date: 2026-04-30 09:05:11.848725-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0b45019a2a'
down_revision: Union[str, None] = 'b07f06943d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ordenes_compra', 'origen',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('planes_produccion_numero_parte_key', 'planes_produccion', type_='unique')
    op.create_foreign_key('fk_planes_produccion_numero_parte', 'planes_produccion', 'inventario_planta', ['numero_parte'], ['codigo'])
    op.alter_column('productos', 'linea_lg',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.alter_column('suministros_silo', 'kg_restantes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suministros_silo', 'kg_restantes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('productos', 'linea_lg',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("''::character varying"),
               nullable=False)
    op.drop_constraint('fk_planes_produccion_numero_parte', 'planes_produccion', type_='foreignkey')
    op.create_unique_constraint('planes_produccion_numero_parte_key', 'planes_produccion', ['numero_parte'], postgresql_nulls_not_distinct=False)
    op.alter_column('ordenes_compra', 'origen',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'FINANZAS'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###