"""reemplazar ordenes_traslado_produccion por registros_salida_produccion

Revision ID: 887b6cbdf40c
Revises: 20260803_impresion_fmt
Create Date: 2026-08-06 10:53:03.284692-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '887b6cbdf40c'
down_revision: Union[str, None] = '20260803_impresion_fmt'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_salida_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('lote_id', sa.String(length=150), nullable=False),
    sa.Column('sku_producto', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('ubicacion_almacen_nombre', sa.String(length=200), nullable=False),
    sa.Column('ubicacion_produccion_nombre', sa.String(length=200), nullable=False),
    sa.Column('creado_por', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_salida_produccion_fecha'), 'registros_salida_produccion', ['fecha'], unique=False)
    op.create_index(op.f('ix_registros_salida_produccion_id'), 'registros_salida_produccion', ['id'], unique=False)
    op.create_index(op.f('ix_registros_salida_produccion_lote_id'), 'registros_salida_produccion', ['lote_id'], unique=False)
    op.create_index(op.f('ix_registros_salida_produccion_sku_producto'), 'registros_salida_produccion', ['sku_producto'], unique=False)
    op.drop_index(op.f('ix_ordenes_traslado_produccion_id'), table_name='ordenes_traslado_produccion')
    op.drop_index(op.f('ix_ordenes_traslado_produccion_id_traslado'), table_name='ordenes_traslado_produccion')
    op.drop_index(op.f('ix_ordenes_traslado_produccion_status'), table_name='ordenes_traslado_produccion')
    op.drop_table('ordenes_traslado_produccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_traslado_produccion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_traslado', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('op_id_origen', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('linea_produccion_destino', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('historial', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ordenes_traslado_produccion_pkey'))
    )
    op.create_index(op.f('ix_ordenes_traslado_produccion_status'), 'ordenes_traslado_produccion', ['status'], unique=False)
    op.create_index(op.f('ix_ordenes_traslado_produccion_id_traslado'), 'ordenes_traslado_produccion', ['id_traslado'], unique=True)
    op.create_index(op.f('ix_ordenes_traslado_produccion_id'), 'ordenes_traslado_produccion', ['id'], unique=False)
    op.drop_index(op.f('ix_registros_salida_produccion_sku_producto'), table_name='registros_salida_produccion')
    op.drop_index(op.f('ix_registros_salida_produccion_lote_id'), table_name='registros_salida_produccion')
    op.drop_index(op.f('ix_registros_salida_produccion_id'), table_name='registros_salida_produccion')
    op.drop_index(op.f('ix_registros_salida_produccion_fecha'), table_name='registros_salida_produccion')
    op.drop_table('registros_salida_produccion')
    # ### end Alembic commands ###