"""crear_tbl_prov

Revision ID: aa86a080294c
Revises: rep_manual
Create Date: 2026-05-22 15:54:05.825347-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa86a080294c'
down_revision: Union[str, None] = 'rep_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('lead_time_dias', sa.Integer(), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=100), nullable=True),
    sa.Column('estatus_calidad', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_rfc'), 'proveedores', ['rfc'], unique=True)
    op.create_table('proveedor_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sku_material', sa.String(length=100), nullable=False),
    sa.Column('codigo_proveedor', sa.String(length=100), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedor_materiales_id'), 'proveedor_materiales', ['id'], unique=False)
    op.create_index(op.f('ix_proveedor_materiales_sku_material'), 'proveedor_materiales', ['sku_material'], unique=False)
    op.add_column('ordenes_compra', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ordenes_compra', 'proveedores', ['proveedor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('plan_inyeccion', 'cav',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'descripcion',
               existing_type=sa.VARCHAR(length=300),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cliente',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'peso',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'cav_bom',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'ciclo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'maquina',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'cav_real',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'ciclo_real',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'tiempo_trabajo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('reportes_manuales_inyeccion', 'cambio_molde',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'ajustes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'arranque_paro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'mantenimiento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'molde_danado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'falta_personal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'falta_material',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'otro_paro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'soldar_puerta_ejector',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'estopero',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'bomba_hidraulica',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'motor_hidraulico',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'manguera_hidraulica',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'valvula_hidraulica',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'reloj',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'caldera',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'sensor_seguridad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'falta_aire',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'fuga_aceite',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'electrico',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'tolva_tapada',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'extra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_falta_llenado',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_cruda',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_quebrada',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_hinchada',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_arranque',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_fuera_dimension',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_pandeada',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_aplastada_molde',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'tiempo_paro_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_buena',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_meta_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_meta_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reportes_manuales_inyeccion', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_meta_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_meta_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_buena',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'tiempo_paro_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_aplastada_molde',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_pandeada',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_fuera_dimension',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_arranque',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_hinchada',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_quebrada',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_cruda',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'scrap_falta_llenado',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'extra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'tolva_tapada',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'electrico',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'fuga_aceite',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'falta_aire',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'sensor_seguridad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'caldera',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'reloj',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'valvula_hidraulica',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'manguera_hidraulica',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'motor_hidraulico',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'bomba_hidraulica',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'estopero',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'soldar_puerta_ejector',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'otro_paro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'falta_material',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'falta_personal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'molde_danado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'mantenimiento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'arranque_paro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'ajustes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cambio_molde',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'produccion_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'tiempo_trabajo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'ciclo_real',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cav_real',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'maquina',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'ciclo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cav_bom',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'peso',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'cliente',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'descripcion',
               existing_type=sa.VARCHAR(length=300),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('reportes_manuales_inyeccion', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('plan_inyeccion', 'cav',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_constraint(None, 'ordenes_compra', type_='foreignkey')
    op.drop_column('ordenes_compra', 'proveedor_id')
    op.drop_index(op.f('ix_proveedor_materiales_sku_material'), table_name='proveedor_materiales')
    op.drop_index(op.f('ix_proveedor_materiales_id'), table_name='proveedor_materiales')
    op.drop_table('proveedor_materiales')
    op.drop_index(op.f('ix_proveedores_rfc'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###